### PR TITLE
add link to environment variable documentation

### PR DESCRIPTION
**Pull request by putianyi889**

### CODE REVIEW

**Comment by simonbyrne** [comment]
That link points toward the julia binary environment variables, these are different ones, so I'm not sure what the benefit would be.

**Comment by putianyi889** [comment]
The first time I used MathLink I had to search for how to set the environment variables. This link makes it easier

**Comment by fremling** [comment]
I think putting a link there makes sense. It a good service to users.

**Comment by simonbyrne** [comment]
Fair enough.

**Pull request merged**
