### PR TITLE
W_cmd macro for parsing Wolfram Language expressions

### LINKED ISSUE #15: Additional macro for copy/pastable Mathematica expressions
The current syntax is nice to write new code in julia using mathematica functions, but it is cumbersome to port existing code written in Mathematica.
Maybe a new string macro like
```julia
WL"Sin[1]" # -> WEpr
```
would be good. Since this probably requires a Mathematica parser it is quite a lot of work.

### PR DESCRIPTION
**Pull request by simonbyrne**
Fixes #15

### CODE REVIEW

**Comment by simonbyrne** [comment]
@BeastyBlacksmith would this solve your problem?

**Comment by BeastyBlacksmith** [comment]
This is definitely a good thing to have!
But something is a bit off. Here is a test case:
```julia
julia> W`v[n1_, n2_] := Module[{r1, r1s, r2, R1, R2},
          r2 = R1/(2 m R1 - 1);
          r1s = R1 /. Solve[n1 R1^2 + n2 r2^2 == 1, R1];
          r1 = r1s[[FirstPosition[r1s /. m -> Sqrt[n1 + n2], 
               n_ /; n == 1/Sqrt[n1 + n2]]]] // Simplify;
          r2 = r2 /. R1 -> r1 // Simplify;
          n1 r1^3 + n2 (r2)^3
          ];
          v[n,n]//FullSimplify` |> weval
W"Null"
```
Expected outcome:
```julia
julia> W`{-((n - (2 m^2 Sqrt[4 m^2 + n])/Sqrt[n] + Sqrt[n] Sqrt[4 m^2 + n])/(
         4 m^3))}`
W"List"(W"Times"(-1, W"Times"(W"Plus"(W"n", W"Times"(-1, W"Times"(2, W"Power"(W"m", 2), W"Sqrt"(W"Plus"(W"Times"(4, W"Power"(W"m", 2)), W"n"))), W"Power"(W"Sqrt"(W"n"), -1)), W"Times"(W"Sqrt"(W"n"), W"Sqrt"(W"Plus"(W"Times"(4, W"Power"(W"m", 2)), W"n")))), W"Power"(W"Times"(4, W"Power"(W"m", 3)), -1))))
```

**Comment by simonbyrne** [comment]
Try it out now (it seems I needed to use `StandardForm` instead of `InputForm`).

Note that you can also use triple backticks for multiline expressions:
W```
v[n1_, n2_] := Module[{r1, r1s, r2, R1, R2},
          r2 = R1/(2 m R1 - 1);
          r1s = R1 /. Solve[n1 R1^2 + n2 r2^2 == 1, R1];
          r1 = r1s[[FirstPosition[r1s /. m -> Sqrt[n1 + n2], 
               n_ /; n == 1/Sqrt[n1 + n2]]]] // Simplify;
          r2 = r2 /. R1 -> r1 // Simplify;
          n1 r1^3 + n2 (r2)^3
          ];
v[n,n]//FullSimplify
``` |> weval

**Comment by BeastyBlacksmith** [comment]
Very nice :), this works

**Comment by BeastyBlacksmith** [comment]
Now we'd need a way to replace parameters with values before evaluation.
Either adding interpolation here ala
```julia
W`Sin[$(1+1)]` # W"Sin"(2)
```
or something like
```julia
replace(W"Sin"(W"n"), W"n" => 1+1) # W"Sin"(2)
```

**Comment by BeastyBlacksmith** [comment]
Actually already possible with
```julia
W"Set"(W"n",1+1)
W`Sin[n]` |> weval
```
Having some nice syntax for this would be a nice to have.

**Comment by simonbyrne** [comment]
> ```julia
> W`Sin[$(1+1)]` # W"Sin"(2)
> ```

The main challenge with this is that `$` is allowed to be used in a variable name (see [here](https://mathematica.stackexchange.com/questions/25183/what-is-sign-in-mathematica)). I'm not sure how best to do this, but perhaps open a new issue to discuss it.

**Pull request merged**
