### PR TITLE
Support for Julia v1.0

### PR DESCRIPTION
**Pull request by ahumenberger**

### CODE REVIEW

**Comment by MikeInnes** [comment]
Awesome! While you're in the code, any chance you could add some tests just to sanity check that this thing works? Then I can test it on my local machine and merge.

**Comment by MasonProtter** [comment]
It's getting there, but there still appear to be some bugs to work out:
```julia
julia> using MathLink

julia> @mmimport(Integrate)
Integrate (generic function with 1 method)

julia> @mmimport(D)
D (generic function with 1 method)

julia> @mmimport(Prime(Integer)::Int)
Prime (generic function with 1 method)

julia> @mmacro(Integrate)
@Integrate (macro with 1 method)

julia> @mmacro(Sin)
@Sin (macro with 1 method)

julia> @Sin(x)
Sin[:x]

julia> @Integrate(Sin(x), x)
Times[-1, Cos[:x]]

julia> @Integrate(Sin(x)^2 + 1, x)
Plus[Times[3//2, :x], Times[-1//4, Sin[Times[2, :x]]]]

julia> @Integrate(Sin(x)^2 + 1, {x, -1, 1})
Plus[3, Times[-1//2, Sin[2]]]

julia> @Integrate(Sin(x)^y + 1, {x, -1, 1})
Plus[2, Times[1//2, Plus[1, Power[-1, :y]], Plus[Times[Power[2, Times[-1, :y]], :Pi, Power[Gamma[Plus[1, Times[1//2, :y]]], -2], Gamma[Plus[1, :y]]], Times[-2, Cos[1], Hypergeometric2F1[1//2, Times[1//2, Plus[1, Times[-1, :y]]], 3//2, Power[Cos[1], 2]]]]]]

julia> @mmacro(D)
@D (macro with 1 method)

julia> @D(x^2, x)
Times[2, :x]

julia> @D(Integrate(Sin(x)^y, {x, -1, 1}), y)
┌ Warning: Error occured in meval: you may need to restart Julia/MathLink
└ @ MathLink ~/.julia/packages/MathLink/eqIci/src/MathLink.jl:104
ERROR: MathLink Error 3 in MLGetFunction: MLGet out of sequence.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] mlerror(::Ptr{Nothing}, ::String) at /Users/mason/.julia/packages/MathLink/eqIci/src/low_level.jl:103
 [3] GetFunction at /Users/mason/.julia/packages/MathLink/eqIci/src/low_level.jl:162 [inlined]
 [4] get!(::Ptr{Nothing}) at /Users/mason/.julia/packages/MathLink/eqIci/src/MathLink.jl:157
 [5] (::getfield(MathLink, Symbol("##9#10")){Ptr{Nothing}})(::Int64) at ./none:0
 [6] iterate at ./generator.jl:47 [inlined]
 [7] collect_to!(::Array{MExpr{:Cos},1}, ::Base.Generator{UnitRange{Int64},getfield(MathLink, Symbol("##9#10")){Ptr{Nothing}}}, ::Int64, ::Int64) at ./array.jl:651
 [8] collect_to_with_first!(::Array{MExpr{:Cos},1}, ::MExpr{:Cos}, ::Base.Generator{UnitRange{Int64},getfield(MathLink, Symbol("##9#10")){Ptr{Nothing}}}, ::Int64) at ./array.jl:630
 [9] collect(::Base.Generator{UnitRange{Int64},getfield(MathLink, Symbol("##9#10")){Ptr{Nothing}}}) at ./array.jl:611
 [10] get!(::Ptr{Nothing}) at /Users/mason/.julia/packages/MathLink/eqIci/src/MathLink.jl:158
 [11] (::getfield(MathLink, Symbol("##9#10")){Ptr{Nothing}})(::Int64) at ./none:0
 [12] iterate at ./generator.jl:47 [inlined]
 [13] collect_to!(::Array{MExpr{:Times},1}, ::Base.Generator{UnitRange{Int64},getfield(MathLink, Symbol("##9#10")){Ptr{Nothing}}}, ::Int64, ::Int64) at ./array.jl:651
 [14] collect_to_with_first!(::Array{MExpr{:Times},1}, ::MExpr{:Times}, ::Base.Generator{UnitRange{Int64},getfield(MathLink, Symbol("##9#10")){Ptr{Nothing}}}, ::Int64) at ./array.jl:630
 [15] collect(::Base.Generator{UnitRange{Int64},getfield(MathLink, Symbol("##9#10")){Ptr{Nothing}}}) at ./array.jl:611
 [16] get!(::Ptr{Nothing}) at /Users/mason/.julia/packages/MathLink/eqIci/src/MathLink.jl:158
 [17] (::getfield(MathLink, Symbol("##9#10")){Ptr{Nothing}})(::Int64) at ./none:0
 [18] iterate at ./generator.jl:47 [inlined]
 [19] collect_to!(::Array{MExpr,1}, ::Base.Generator{UnitRange{Int64},getfield(MathLink, Symbol("##9#10")){Ptr{Nothing}}}, ::Int64, ::Int64) at ./array.jl:651
 [20] collect_to!(::Array{MExpr{:Rational},1}, ::Base.Generator{UnitRange{Int64},getfield(MathLink, Symbol("##9#10")){Ptr{Nothing}}}, ::Int64, ::Int64) at ./array.jl:659
 [21] collect_to_with_first!(::Array{MExpr{:Rational},1}, ::MExpr{:Rational}, ::Base.Generator{UnitRange{Int64},getfield(MathLink, Symbol("##9#10")){Ptr{Nothing}}}, ::Int64) at ./array.jl:630
 [22] collect(::Base.Generator{UnitRange{Int64},getfield(MathLink, Symbol("##9#10")){Ptr{Nothing}}}) at ./array.jl:611
 [23] get!(::Ptr{Nothing}) at /Users/mason/.julia/packages/MathLink/eqIci/src/MathLink.jl:158
 [24] (::getfield(MathLink, Symbol("##9#10")){Ptr{Nothing}})(::Int64) at ./none:0
 [25] iterate at ./generator.jl:47 [inlined]
 [26] collect_to!(::Array{MExpr{:Times},1}, ::Base.Generator{UnitRange{Int64},getfield(MathLink, Symbol("##9#10")){Ptr{Nothing}}}, ::Int64, ::Int64) at ./array.jl:651
 [27] collect_to_with_first!(::Array{MExpr{:Times},1}, ::MExpr{:Times}, ::Base.Generator{UnitRange{Int64},getfield(MathLink, Symbol("##9#10")){Ptr{Nothing}}}, ::Int64) at ./array.jl:630
 [28] collect(::Base.Generator{UnitRange{Int64},getfield(MathLink, Symbol("##9#10")){Ptr{Nothing}}}) at ./array.jl:611
 [29] get!(::Ptr{Nothing}) at /Users/mason/.julia/packages/MathLink/eqIci/src/MathLink.jl:158
 [30] get!(::Ptr{Nothing}, ::Type) at /Users/mason/.julia/packages/MathLink/eqIci/src/MathLink.jl:147
 [31] handle_packets(::Ptr{Nothing}, ::Type) at /Users/mason/.julia/packages/MathLink/eqIci/src/MathLink.jl:127
 [32] meval(::Ptr{Nothing}, ::Expr, ::Type) at /Users/mason/.julia/packages/MathLink/eqIci/src/MathLink.jl:100
 [33] meval at /Users/mason/.julia/packages/MathLink/eqIci/src/MathLink.jl:94 [inlined]
 [34] meval(::Expr) at /Users/mason/.julia/packages/MathLink/eqIci/src/MathLink.jl:93
 [35] top-level scope at none:0

julia> @D(x^2, x)
┌ Warning: Error occured in meval: you may need to restart Julia/MathLink
└ @ MathLink ~/.julia/packages/MathLink/eqIci/src/MathLink.jl:104
ERROR: MathLink Error 3 in MLPutFunction: MLGet out of sequence.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] mlerror(::Ptr{Nothing}, ::String) at /Users/mason/.julia/packages/MathLink/eqIci/src/low_level.jl:103
 [3] PutFunction at /Users/mason/.julia/packages/MathLink/eqIci/src/low_level.jl:107 [inlined]
 [4] put! at /Users/mason/.julia/packages/MathLink/eqIci/src/MathLink.jl:177 [inlined]
 [5] put!(::Ptr{Nothing}, ::MExpr{:EvaluatePacket}) at /Users/mason/.julia/packages/MathLink/eqIci/src/MathLink.jl:188
 [6] meval(::Ptr{Nothing}, ::Expr, ::Type) at /Users/mason/.julia/packages/MathLink/eqIci/src/MathLink.jl:98
 [7] meval at /Users/mason/.julia/packages/MathLink/eqIci/src/MathLink.jl:94 [inlined]
 [8] meval(::Expr) at /Users/mason/.julia/packages/MathLink/eqIci/src/MathLink.jl:93
 [9] top-level scope at none:0

```

**Comment by ahumenberger** [comment]
There seems to be some sort of miscommunication with the MathLink library, but I'm not a MathLink expert. I just updated the Julia package in terms of syntax changes and similar stuff, so I assume that this issue already existed before.
Anyway, after a quick look, it might be that we're dealing with the situation described here:
http://mathforum.org/kb/message.jspa?messageID=790222

**Comment by simonbyrne** [comment]
Superseded by #12.

**Pull request closed without merging**
