### PR TITLE
mathlink macos wolfram engine

### PR DESCRIPTION
**Pull request by fgerick**
This took me a while to find when using the free Wolfram Engine. With Mathematica this is automatically linked, so no problem.

### CODE REVIEW

**Comment by simonbyrne** [comment]
This should work already. I don't have Wolfram Engine installed, but can you check the logic used here:
https://github.com/JuliaInterop/MathLink.jl/blob/ab8ed479f82d2e5e034cebbf98a606a2298b4a91/deps/build.jl#L19-L28

**Comment by fgerick** [comment]
without setting any environment variables I get this :

```julia
(@v1.6) pkg> build MathLink
    Building MathLink → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/456465e96317c706dc2e782f441bff3053ff843e/build.log`
ERROR: Error building `MathLink`:
ERROR: LoadError: Could not find Mathematica or Wolfram Engine installation.
Please set the `JULIA_MATHLINK` and `JULIA_MATHKERNEL` variables.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] find_lib_ker()
   @ Main ~/.julia/packages/MathLink/f5mIR/deps/build.jl:85
 [3] top-level scope
   @ ~/.julia/packages/MathLink/f5mIR/deps/build.jl:88
 [4] include(fname::String)
   @ Base.MainInclude ./client.jl:444
 [5] top-level scope
   @ none:5
in expression starting at /Users/felixger/.julia/packages/MathLink/f5mIR/deps/build.jl:88
```

because

```julia
julia> readlines(`mdfind "kMDItemCFBundleIdentifier == 'com.wolfram.engine'"`)
String[]
```

did I miss something during the installation of the Wolfram Engine? `which wolframscript` gives `/usr/local/bin/wolframscript`, which is a softlink ` /usr/local/bin/wolframscript -> /Applications/WolframScript.app/Contents/MacOS/wolframscript`

**Comment by simonbyrne** [comment]
what does this give?
```
readlines(`mdfind "kMDItemCFBundleIdentifier == 'com.wolfram.*'"`)
```

**Comment by fgerick** [comment]
```
julia> readlines(`mdfind "kMDItemCFBundleIdentifier == 'com.wolfram.*'"`)
3-element Vector{String}:
 "/Applications/Wolfram Player.app"
 "/Applications/Wolfram Engine.app"
 "/Applications/WolframScript.app"
```

**Comment by simonbyrne** [comment]
Thanks!

**Pull request merged**
